apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.shellOperator.validatingWebhookServiceName }}
  labels:
    app: cosign-validator
spec:
  ports:
    - name: validating-webhook
      port: 443
      targetPort: 9680
      protocol: TCP
  selector:
    app: cosign-validator
